### ISSUE TITLE
KeyError: 'original_files'

### ISSUE THREAD

**Issue by cosmiccapybara** [kundajelab/ENCODE_downloader#14]
Hello, I am trying to download multiple files by providing a list of file IDs:

python /g/data/zk16/software/encode_downloader.py acc_ids.txt

========== ENCFF093VXI ==========
Traceback (most recent call last):
  File "/g/data/zk16/software/encode_downloader.py", line 414, in <module>
    main()
  File "/g/data/zk16/software/encode_downloader.py", line 230, in main
    for org_f in json_data_exp['original_files']:
KeyError: 'original_files'

**Comment by leepc12** [comment]
I'm sorry that this tools is no longer maintained.
Please add a single line to skip file accessions without such key. Something like
```python

# add this to line 229
if 'original_files' not in json_data_exp:
    continue

for org_f in json_data_exp['original_files']:
...
```
