### ISSUE TITLE
Error in downloading data with a search Query

### ISSUE THREAD

**Issue by manyu90** [kundajelab/ENCODE_downloader#5]
I ran the command:
```
python ENCODE_downloader.py "https://www.encodeproject.org/search/?type=Experiment&assay_title=ChIP-seq&target.investigated_as=transcription+factor&files.file_type=bed+narrowPeak&replicates.library.biosample.donor.organism.scientific_name=Homo+sapiens&biosample_type=immortalized+cell+line&assembly=GRCh38&biosample_term_name=K562&assay_title=ChIP-seq" --dir ./ --file-types narrowPeak --assemblies GRCh38 --assembly-map Homo+sapiens:GRCh38



```
and got the following error

```
Traceback (most recent call last):
  File "ENCODE_downloader.py", line 414, in <module>
    main()
  File "ENCODE_downloader.py", line 381, in main
    max_num_files = max( [len(all_file_metadata[acc_id]) for acc_id in all_file_metadata] )
ValueError: max() arg is an empty sequence
```

I got messages on the screen seeming like downloads were happening, but the download folder is empty

**Comment by leepc12** [comment]
Please try with `--file-types bed:narrowPeak`.

**Comment by manyu90** [comment]
Thanks, this worked
