### ISSUE TITLE
Error message and less files downloaded

### ISSUE THREAD

**Issue by lswilson98** [kundajelab/ENCODE_downloader#8]
I have received another error:

========== ENCSR402HFW ==========
assembly: GRCh38
Exception caught, retrying in 120 seconds...
Traceback (most recent call last):
  File "/home/share/dcyleung/Program/ENCODE_downloader-master/encode_downloader.py", line 411, in <module>
    main()
  File "/home/share/dcyleung/Program/ENCODE_downloader-master/encode_downloader.py", line 243, in main
    retry_cnt += 1
UnboundLocalError: local variable 'retry_cnt' referenced before assignment

This caused only 115 files to be downloaded, instead of 228. Is this due to the error? and how do I resolve this. 

Thanks,

Lili

**Comment by leepc12** [comment]
Thanks for reporting this. It's fixed now.
