### ISSUE TITLE
KeyError for URL based download

### ISSUE THREAD

**Issue by stolarczyk** [kundajelab/ENCODE_downloader#9]
I'm aware that this is probably a data source specific issue, but decided to report here anyway.
```
[mjs5kd@udc-ba36-36 regions](master): python3.6 encode_downloader.py "https://www.encodeproject.org/experiments/ENCSR985TIQ/" --file-types bed
['ENCSR985TIQ']
========== ENCSR985TIQ ==========
assembly: mm10
Traceback (most recent call last):
  File "/home/mjs5kd/code/ENCODE_downloader/encode_downloader.py", line 416, in <module>
    main()
  File "/home/mjs5kd/code/ENCODE_downloader/encode_downloader.py", line 221, in main
    assay_title = json_data_exp['assay_title']
KeyError: 'assay_title'
```

**Comment by leepc12** [comment]
Fixed
